import { NextResponse } from "next/server";
import { z } from "zod";
import { getOrCreateAudioUrl } from "@/lib/tts-server";
import { getVoiceEntry } from "@/lib/voice-catalog";

/**
 * Public TTS endpoint scoped to a tiny whitelist of phrases used on
 * the landing page demo. Lets unauthenticated marketing visitors
 * actually hear the native-speaker voice when they click the
 * speaker button on the demo flashcard, without us having to
 * open up the main /api/tts route to anonymous traffic.
 *
 * The whitelist is the only abuse surface — it caps the audio
 * combinations to four. Each (text, languageCode) hash gets
 * generated by Google Cloud TTS on first request, persisted to
 * Supabase Storage, then served from the cache forever.
 */

const RequestSchema = z.object({
  text: z.string().min(1).max(120),
  languageCode: z.enum(["es-MX", "en-GB", "fr-FR"]),
});

// Hard-coded whitelist. If the demo cards on the landing page
// change, update this list. Anything not on the list returns 400
// — preventing this route from being used as a free general-
// purpose TTS endpoint.
const ALLOWED: Record<string, ReadonlySet<string>> = {
  "es-MX": new Set(["Aunque sea duro, hay que seguir."]),
  "en-GB": new Set([
    "Even if it's hard, we have to continue.",
    "To have a frog in one's throat",
  ]),
  "fr-FR": new Set(["Avoir un chat dans la gorge"]),
};

export async function POST(request: Request) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = RequestSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Invalid request" },
      { status: 400 }
    );
  }
  const { text, languageCode } = parsed.data;

  const allowed = ALLOWED[languageCode];
  if (!allowed || !allowed.has(text)) {
    return NextResponse.json(
      { error: "Phrase not on the demo whitelist" },
      { status: 400 }
    );
  }

  const entry = getVoiceEntry(languageCode);
  if (!entry) {
    return NextResponse.json(
      { error: `No voice configured for ${languageCode}` },
      { status: 500 }
    );
  }

  try {
    const audioUrl = await getOrCreateAudioUrl(text, entry);
    return NextResponse.json({ audioUrl });
  } catch (err) {
    const message = err instanceof Error ? err.message : "TTS generation failed";
    console.error("[landing/tts]", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
